export const SELECT_POINT = 'SELECT_POINT';

export const SELECT_AREA = 'SELECT_AREA';

export const GET_POINTS = 'GET_POINTS';

export const GET_USER_HISTORY = 'GET_USER_HISTORY';

export const GET_SUBURB_DATA = 'GET_SUBURB_DATA';

export const GET_MELBOURNE_DATA = 'GET_MELBOURNE_DATA';

export const STATS_DRAWER = 'STATS_DRAWER';